#
warnings_are_errors: false

language: r

os:
  - linux
  - osx

r:
  - release

branches:
  only:
  - master

sudo: false

cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

before_deploy:
  # - export TRAVIS_TAG=${$(sed -n "s/Version: *\([^ ]*\)/\1/p" DESCRIPTION)}
    - export TRAVIS_TAG="FLCore_2.6.12"
    
deploy:
  provider: releases
  api_key:
    secure: hd/AVHdIxPFEYvx66wCgXHfm0mFr/SGgiwRks8q9vSVHZwTrKoOyutt80p5lbPLSOaLIb818ZBAaxYuaKACoxZWblS/Rm+VfR3q/ct+y5Mx9EUQItuHTWbD/Y7wwcoa9myvh45U72ubve+UWbBjJUDNYrGrlX/OaJcIMu8QfGx4=
  skip_cleanup: true
  draft: true
  file: FLCore_${TRAVIS_TAG}.tgz
  on:
    os: osx
    branch: master
    repo: flr/FLCore
