language: r

warnings_are_errors: false

os:
- linux
- osx

r:
- release

branches:
  only:
  - master
  # RUN also for version tags, v*.*.*
  - /^v.*$/

sudo: false

cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

before_deploy:
  # EXTRACT pkg version numbers from git tag
  - export PKGVERS = ${TRAVIS_TAG//[!0-9.]/}

deploy:
  provider: releases
  api_key:
    secure: QrWCUrkEVOwPitBzGoIoK8zp2Mk4SL0KTnygW9YtVwFCe+vkbEAfvRpRRQ9IvjPUberQT1WvysWr/oM232QtL+g7TeEad0uB5oLMrGq6lyUBgaUnkzRShIKMbUzXOH3i2EW4Bv2mUaKf02nkiRNcNIG0t3SBfwbgMHwhf/VWATc=
  skip_cleanup: true
  file: FLCore_${PKGVERS}.tgz
  on:
    os: osx
    branch: master
    repo: flr/FLCore
    tag: true
